package forms;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;


public class gamePlay extends javax.swing.JFrame {

    /**
     * Creates new form gamePlay
     */
    public gamePlay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        infoMenu = new javax.swing.JPanel();
        popLbl = new javax.swing.JLabel();
        goldLbl = new javax.swing.JLabel();
        growLbl = new javax.swing.JLabel();
        gRateLbl = new javax.swing.JLabel();
        popNum = new javax.swing.JLabel();
        goldNum = new javax.swing.JLabel();
        gRateNum = new javax.swing.JLabel();
        growNum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        infoMenu.setBackground(new java.awt.Color(0, 0, 0));

        popLbl.setBackground(new java.awt.Color(0, 0, 0));
        popLbl.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        popLbl.setForeground(new java.awt.Color(0, 204, 0));
        popLbl.setText("Population:");

        goldLbl.setBackground(new java.awt.Color(0, 0, 0));
        goldLbl.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        goldLbl.setForeground(new java.awt.Color(0, 204, 0));
        goldLbl.setText("Gold:");

        growLbl.setBackground(new java.awt.Color(0, 0, 0));
        growLbl.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        growLbl.setForeground(new java.awt.Color(0, 204, 0));
        growLbl.setText("Growth Rate:");

        gRateLbl.setBackground(new java.awt.Color(0, 0, 0));
        gRateLbl.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        gRateLbl.setForeground(new java.awt.Color(0, 204, 0));
        gRateLbl.setText("Gold Rate:");

        popNum.setBackground(new java.awt.Color(0, 0, 0));
        popNum.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        popNum.setForeground(new java.awt.Color(0, 204, 0));
        popNum.setText("MockData Here");

        goldNum.setBackground(new java.awt.Color(0, 0, 0));
        goldNum.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        goldNum.setForeground(new java.awt.Color(0, 204, 0));
        goldNum.setText("MockData Here");

        gRateNum.setBackground(new java.awt.Color(0, 0, 0));
        gRateNum.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        gRateNum.setForeground(new java.awt.Color(0, 204, 0));
        gRateNum.setText("MockData Here");

        growNum.setBackground(new java.awt.Color(0, 0, 0));
        growNum.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        growNum.setForeground(new java.awt.Color(0, 204, 0));
        growNum.setText("MockData Here");

        javax.swing.GroupLayout gl_infoMenu = new javax.swing.GroupLayout(infoMenu);
        infoMenu.setLayout(gl_infoMenu);
        gl_infoMenu.setHorizontalGroup(
            gl_infoMenu.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_infoMenu.createSequentialGroup()
                .addContainerGap()
                .addGroup(gl_infoMenu.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gl_infoMenu.createSequentialGroup()
                        .addGroup(gl_infoMenu.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(popLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(goldLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)
                        .addGroup(gl_infoMenu.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(goldNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(popNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gl_infoMenu.createSequentialGroup()
                        .addGroup(gl_infoMenu.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gRateLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(growLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(gl_infoMenu.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(growNum, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(gRateNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        gl_infoMenu.setVerticalGroup(
            gl_infoMenu.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_infoMenu.createSequentialGroup()
                .addContainerGap()
                .addGroup(gl_infoMenu.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(popLbl)
                    .addComponent(popNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gl_infoMenu.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goldLbl)
                    .addComponent(goldNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gl_infoMenu.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(growLbl)
                    .addComponent(growNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gl_infoMenu.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gRateLbl)
                    .addComponent(gRateNum))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout gl_menuBar = new javax.swing.GroupLayout(menuBar);
        gl_menuBar.setHorizontalGroup(
        	gl_menuBar.createParallelGroup(Alignment.TRAILING)
        		.addGroup(gl_menuBar.createSequentialGroup()
        			.addComponent(infoMenu, GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gl_menuBar.setVerticalGroup(
        	gl_menuBar.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_menuBar.createSequentialGroup()
        			.addGap(0, 0, Short.MAX_VALUE)
        			.addGroup(gl_menuBar.createParallelGroup(Alignment.LEADING)
        				.addComponent(jPanel2, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jPanel1, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(infoMenu, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        );
        menuBar.setLayout(gl_menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 300, Short.MAX_VALUE)
                .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gamePlay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel popLbl;
    private javax.swing.JLabel goldLbl;
    private javax.swing.JLabel growLbl;
    private javax.swing.JLabel gRateLbl;
    private javax.swing.JLabel popNum;
    private javax.swing.JLabel goldNum;
    private javax.swing.JLabel gRateNum;
    private javax.swing.JLabel growNum;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel menuBar;
    private javax.swing.JPanel infoMenu;
}
